In [1]:
import weapon_data as weapons

D:\z_outsourced_programs\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
train_data, test_data = weapons.get_data(debug=True) 
print(train_data.standardized_max_values)
print(train_data.standardized_min_values)
print(test_data.standardized_max_values)
print(test_data.standardized_min_values)

Feature columns to tensor variables dictionary:
_NumericColumn(key='damages_first', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None) = []
_NumericColumn(key='damages_last', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None) = []
_NumericColumn(key='distances_first', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None) = []
_NumericColumn(key='distances_last', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None) = []
_IndicatorColumn(categorical_column=_VocabularyListCategoricalColumn(key='firemode', vocabulary_list=('Automatic', 'Semi', 'Single'), dtype=tf.string, default_value=-1, num_oov_buckets=0)) = []
_NumericColumn(key='hiprecoildec', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None) = []
_NumericColumn(key='hiprecoilright', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None) = []
_NumericColumn(key='hiprecoilup', shape=(1,), default_value=None, dtype=tf.float32, normal

In [3]:
test_data._feature_cols_to_vars_dict

{_IndicatorColumn(categorical_column=_VocabularyListCategoricalColumn(key='firemode', vocabulary_list=('Automatic', 'Semi', 'Single'), dtype=tf.string, default_value=-1, num_oov_buckets=0)): [],
 _IndicatorColumn(categorical_column=_VocabularyListCategoricalColumn(key='type', vocabulary_list=('Shotgun', 'Pistol', 'Rifle', 'SMG', 'Sniper', 'MG'), dtype=tf.string, default_value=-1, num_oov_buckets=0)): [],
 _NumericColumn(key='damages_first', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None): [],
 _NumericColumn(key='damages_last', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None): [],
 _NumericColumn(key='distances_first', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None): [],
 _NumericColumn(key='distances_last', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None): [],
 _NumericColumn(key='hiprecoildec', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None): [],
 _NumericColumn(key='hiprecoilr

In [4]:
print("Training data size %i "%train_data.num_examples)
print("Test data size %i "%test_data.num_examples)
print("Sum of data %i"%(train_data.num_examples+test_data.num_examples))

Training data size 127 
Test data size 21 
Sum of data 148


In [5]:
import tensorflow as tf

def addGeneratedWeapon(generatedWeaponTensorDict, dictToAdd):
    for key, value in generatedWeaponTensorDict.items():
        if key not in dictToAdd:
            dictToAdd[key] = []
        dictToAdd[key].append(value)

def check_data(data):
    genDict = {}

    #print to see if normalized
    print(data.data[0])
    
    #check if unnormalizing and adding works
    var_init = tf.global_variables_initializer()

    batch_size = 1
    with tf.Session() as sess:
        sess.run(var_init)

        for i in range(1):
            batch = data.next_batch(batch_size, shuffle=True)
            #print("Batch size %i" %len(batch))
            data.add_new_weapons_and_restandardize_data(batch)

            
        tensorDict = [data.decode_processed_tensor(b)[0] for b in batch]
        [addGeneratedWeapon(t, genDict) for t in tensorDict]
        #debug_printDict(tensorDict[0])


    #weapons.debug_printDict(genDict)
    print(genDict)


In [6]:
check_data(train_data)
#check_data(test_data)

[-1.47834628 -1.16967347 -0.22998987 -1.05853523 -0.72809373  1.28290036
 -0.61679395 -0.3337167  -0.28161517  0.61328002 -0.48584349 -0.53444912
 -1.18651422 -0.51888293  0.26802014 -0.27490497  3.61915126  3.09569594
 -0.5073714  -0.54398379 -0.36596253 -0.54398379 -0.3796632 ]
Current position in dataset after next_batch = 1
Added new weapon/s! New number of examples in dataset = 128
{'damages_first': ['12.162937399085614'], 'damages_last': ['6.030075549538672'], 'distances_first': ['13.99480528785581'], 'distances_last': ['20.66219613488542'], 'firemode_Automatic': ['-0.0020645831274538895'], 'firemode_Semi': ['-0.0023659540699704773'], 'firemode_Single': ['1.010195544703345'], 'hiprecoildec': ['2.9833859455028495'], 'hiprecoilright': ['1.0032845339602585'], 'hiprecoilup': ['11.315553694101405'], 'hipstandbasespreaddec': ['5.996027556609341'], 'hipstandbasespreadinc': ['1.6521297364325476'], 'initialspeed': ['330.6993883813104'], 'magsize': ['5.915086202887252'], 'reloadempty': ['3

In [7]:
batch = test_data.next_batch(1)

Current position in dataset after next_batch = 1


In [ ]:
weapon_dict, _ = test_data.decode_processed_tensor(batch[0])

In [8]:
batch[0]

array([-1.23029653, -1.03323256, -0.14336529, -0.91073274, -1.04880885,
       -0.63245553,  2.06155281,  0.18639461,  1.60775078,  2.95017835,
       -0.50310997,  0.03193609, -1.30889378, -0.63118823,  0.58731268,
       -0.36727151,  3.082207  ,  3.082207  , -0.48507125, -0.55901699,
       -0.32444284, -0.40824829, -0.55901699])

In [9]:
weapon_dict

{'damages_first': '12.5',
 'damages_last': '6.25',
 'distances_first': '14.0',
 'distances_last': '21.0',
 'firemode_Automatic': '0.0',
 'firemode_Semi': '0.0',
 'firemode_Single': '1.0',
 'hiprecoildec': '6.0',
 'hiprecoilright': '1.2000000476837158',
 'hiprecoilup': '11.0',
 'hipstandbasespreaddec': '4.5',
 'hipstandbasespreadinc': '0.30000001192092896',
 'initialspeed': '333.0',
 'magsize': '2.0',
 'reloadempty': '5.333333492279053',
 'rof': '299.0',
 'shotspershell': '12.0',
 'type_MG': '-2.7755575615628914e-17',
 'type_Pistol': '0.0',
 'type_Rifle': '-2.7755575615628914e-17',
 'type_SMG': '0.0',
 'type_Shotgun': '1.0',
 'type_Sniper': '0.0'}

In [10]:
prepared_for_encoding = test_data.prepare_decoded_tensor_dict_for_encoding(weapon_dict)
original, _ = test_data.encode_features_dict(prepared_for_encoding)
test = test_data.standardize_encoded_data(original[0])

Feature columns to tensor variables dictionary:
_NumericColumn(key='damages_first', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None) = []
_NumericColumn(key='damages_last', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None) = []
_NumericColumn(key='distances_first', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None) = []
_NumericColumn(key='distances_last', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None) = []
_IndicatorColumn(categorical_column=_VocabularyListCategoricalColumn(key='firemode', vocabulary_list=('Automatic', 'Semi', 'Single'), dtype=tf.string, default_value=-1, num_oov_buckets=0)) = []
_NumericColumn(key='hiprecoildec', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None) = []
_NumericColumn(key='hiprecoilright', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None) = []
_NumericColumn(key='hiprecoilup', shape=(1,), default_value=None, dtype=tf.float32, normal

In [11]:
test

array([-1.23029653, -1.03323256, -0.14336529, -0.91073274, -1.04880885,
       -0.63245553, -0.48507125,  0.18639461,  1.60775078,  2.95017835,
       -0.50310997,  0.03193609, -1.30889378, -0.63118823,  0.58731268,
       -0.36727151,  3.082207  , -0.32444284, -0.48507125, -0.55901699,
       -0.32444284, -0.40824829, -0.55901699])

In [12]:
test_data.decode_processed_tensor(test)

({'damages_first': '12.5',
  'damages_last': '6.25',
  'distances_first': '14.0',
  'distances_last': '21.0',
  'firemode_Automatic': '0.0',
  'firemode_Semi': '0.0',
  'firemode_Single': '0.0',
  'hiprecoildec': '6.0',
  'hiprecoilright': '1.2000000476837158',
  'hiprecoilup': '11.0',
  'hipstandbasespreaddec': '4.5',
  'hipstandbasespreadinc': '0.30000001192092896',
  'initialspeed': '333.0',
  'magsize': '2.0',
  'reloadempty': '5.333333492279053',
  'rof': '299.0',
  'shotspershell': '12.0',
  'type_MG': '-2.7755575615628914e-17',
  'type_Pistol': '0.0',
  'type_Rifle': '-2.7755575615628914e-17',
  'type_SMG': '0.0',
  'type_Shotgun': '0.0',
  'type_Sniper': '0.0'},
 array([ 1.25000000e+01,  6.25000000e+00,  1.40000000e+01,  2.10000000e+01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  6.00000000e+00,
         1.20000005e+00,  1.10000000e+01,  4.50000000e+00,  3.00000012e-01,
         3.33000000e+02,  2.00000000e+00,  5.33333349e+00,  2.99000000e+02,
         1.200000

In [13]:
test_data.add_new_weapons_and_restandardize_data(test_data.next_batch(10))

Current position in dataset after next_batch = 11
Added new weapon/s! New number of examples in dataset = 31


In [14]:
test_data.next_batch(10)

Current position in dataset after next_batch = 21


array([[-0.39985327, -0.24782506, -0.39956765, -0.52074564,  0.84983659,
        -0.58976782, -0.43852901,  0.13831796, -1.06338055, -0.65239347,
        -0.78317108,  0.59550076,  1.10863399,  2.14007921,  0.69340237,
         0.29275708, -0.32732684, -0.32732684, -0.43852901, -0.58976782,
         3.80788655, -0.38490018, -0.63960215],
       [-0.03141098, -0.60308874, -0.69544472, -0.59002679, -1.17669681,
         1.6955825 , -0.43852901, -0.3385344 ,  0.32254193,  0.04702235,
        -0.26500364, -0.2626493 , -1.87108148, -0.57643848, -1.34802515,
        -0.39605317, -0.32732684, -0.32732684,  2.28035085, -0.58976782,
        -0.26261287, -0.38490018, -0.63960215],
       [-0.39985327, -0.60308874, -0.24216107, -0.59002679, -1.17669681,
         1.6955825 , -0.43852901, -0.3385344 , -0.55940875, -0.229974  ,
        -0.58885828, -0.43427931, -0.95794287, -0.54814142, -0.85011602,
        -0.39605317, -0.32732684, -0.32732684,  2.28035085, -0.58976782,
        -0.26261287, -0.3849